#ifndef GLASS98_WIDGETS_H
#define GLASS98_WIDGETS_H
#define GLASS98_PANELS 28
#define WIDGET_DESKTOP 22
#define WIDGET_MEMORY 23
#define WIDGET_CALCULATOR 24
#define WIDGET_CHARACTERS 25
#define WIDGET_DAILY 26
#define WIDGET_CLIPBOARD 27
#endif
